AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creating an Ec2 Instance'
Resources:
    Server1:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: YOUR_AMI_ID
            InstanceType: t2.micro
            KeyName: YOUR_KEYPAIR_NAME
